//GET 

export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

//ADD 

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST'
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS'
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE'

//DELETE 

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST'
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS'
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE'

//UPDATE 

export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST'
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS'
export const UPDATE_ITEMS_FAILURE = 'UPDATE_ITEMS_FAILURE'

//SEARCH 

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'

//PAGINATION

export const PAGE_ITEMS_REQUEST = 'PAGE_ITEMS_REQUEST'
export const PAGE_ITEMS_SUCCESS = 'PAGE_ITEMS_SUCCESS'
export const PAGE_ITEMS_FAILURE = 'PAGE_ITEMS_FAILURE'

export const LIMIT = 5